// Generated by Skyramp v1.3.44 on 2026-09-08 21:00:37.877703297 +0000 UTC m=+348.475415206
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_header_subtitle_removed.spec.ts \
// 		--output-dir /home/runner/work/cal.diy/cal.diy/apps/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/cal.diy/cal.diy/.skyramp/login_header_subtitle_removed_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(241000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/auth/login`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await expect(page.getByTestId("login-subtitle")).toBeHidden();
    await expect(page.getByRole("heading", { name: "Cal.diy" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Continue" })).toBeEnabled();
    await expect(page.getByText("Cal.diyEmailPasswordForgot?")).toHaveScreenshot("login-card-header.png", { maxDiffPixelRatio: 0.005 });

    await expect(pageErrors).toHaveLength(0);
});
