// Generated by Skyramp v1.3.44 on 2026-09-08 21:26:37.321146316 +0000 UTC m=+785.397684212
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_credentials_form_renamed_testid.spec.ts \
// 		--output-dir /home/runner/work/cal.diy/cal.diy/apps/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/cal.diy/cal.diy/.skyramp/login_credentials_form_renamed_testid_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(95000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => {
        pageErrors.push(error.message);
    });

    const loginPassword = process.env.SKYRAMP_UI_PASSWORD ?? "definitely-not-the-password";

    await page.goto(`${baseUrl}/auth/login`);
    await expect(page.getByTestId("login-credentials-form")).toBeVisible();
    await page.locator("#email").fill("no-such-account@example.com");
    await page.locator("#password").fill(loginPassword);
    await expect(page.getByRole("heading", { name: "Email or password is incorrect." })).toBeHidden();
    await page.getByRole("button", { name: "Continue" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("heading", { name: "Email or password is" })).toContainText("Email or password is incorrect.");
    await expect(page.getByRole("textbox", { name: "Email" })).toHaveValue("no-such-account@example.com");
    expect(pageErrors).toHaveLength(0);
});
