// Generated by Skyramp v1.3.44 on 2026-09-08 21:06:31.302333996 +0000 UTC m=+342.808742402
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output verify_removed_ui_auth_login.spec.ts \
// 		--output-dir /home/runner/work/cal.diy/cal.diy/apps/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/cal.diy/cal.diy/.skyramp/verify_removed_ui_auth_login_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(107000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/auth/login`);
    await expect(page.getByRole("link", { exact: true, name: "Forgot?" })).toBeHidden();
    await expect(page.locator('a[href="/auth/forgot-password"]')).toHaveCount(0);
    await expect(page.getByRole("textbox", { name: "Password" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Continue" })).toBeEnabled();
    await page.goto(`${baseUrl}/auth/forgot-password`);
    await expect(page).toHaveURL(`${baseUrl}/auth/forgot-password`);
    await expect(page.getByRole("heading", { level: 2 })).toHaveText("Forgot password?");
    await expect(page.getByRole("button", { name: "Send reset email" })).toBeEnabled();

    expect(pageErrors).toHaveLength(0);
});
