// Generated by Skyramp v1.3.44 on 2026-09-08 21:05:58.699238592 +0000 UTC m=+571.514952669
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output verify_removed_ui_login.spec.ts \
// 		--output-dir /home/runner/work/cal.diy/cal.diy/apps/web/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/cal.diy/cal.diy/.skyramp/verify_removed_ui_login_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(77000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/auth/login`);
    await expect(page).toHaveURL(`${baseUrl}/auth/login`);
    await expect(page.getByTestId("login-subtitle")).toBeHidden();
    await expect(page.getByRole("heading", { level: 1 })).toHaveText("Cal.diy");
    await expect(page.getByRole("button", { name: "Continue" })).toBeEnabled();
    expect(pageErrors).toHaveLength(0);
});
